"""empty message

Revision ID: 00081b33af3b
Revises: 22122e1bd0e1
Create Date: 2019-07-29 14:01:26.756359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00081b33af3b'
down_revision = '22122e1bd0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth2_roles', sa.Column('date_created', sa.TIMESTAMP(), nullable=True))
    op.add_column('oauth2_roles', sa.Column('date_last_updated', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth2_roles', 'date_last_updated')
    op.drop_column('oauth2_roles', 'date_created')
    # ### end Alembic commands ###
