"""empty message

Revision ID: 22122e1bd0e1
Revises: 4eea6d5ae1ee
Create Date: 2019-07-29 12:39:11.372720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22122e1bd0e1'
down_revision = '4eea6d5ae1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth2_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role'),
    sa.UniqueConstraint('role')
    )
    op.create_table('roles',
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth2_clients.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['oauth2_roles.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('oauth2_roles')
    # ### end Alembic commands ###
