"""empty message

Revision ID: 339d47a41f8c
Revises: 641292c41442
Create Date: 2019-07-26 07:56:35.822793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339d47a41f8c'
down_revision = '641292c41442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
