"""Add a can_login field to the user model

Revision ID: 3c9238327009
Revises: e0a50f613878
Create Date: 2020-11-04 15:00:40.252347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9238327009'
down_revision = 'e0a50f613878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_login', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_login')
    # ### end Alembic commands ###
