"""empty message

Revision ID: 3ec1a5593d88
Revises: 
Create Date: 2019-07-24 16:12:49.788745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec1a5593d88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_trust',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data_trust_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_trust_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_trust')
    # ### end Alembic commands ###
