"""Create authorized_scopes table

Revision ID: 3f6cee6eb450
Revises: d92fa4b2c4f8
Create Date: 2020-09-29 23:23:03.855651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6cee6eb450'
down_revision = 'd92fa4b2c4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorized_scopes',
                    sa.Column('role_id', sa.String(), nullable=False),
                    sa.Column('scope_id', sa.String(), nullable=False),
                    sa.Column('date_created', sa.TIMESTAMP(), nullable=True),
                    sa.Column('date_last_updated', sa.TIMESTAMP(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['oauth2_roles.id'], ),
                    sa.ForeignKeyConstraint(['scope_id'], ['oauth2_scopes.id'], ),
                    sa.PrimaryKeyConstraint('role_id', 'scope_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorized_scopes')
    # ### end Alembic commands ###
