"""empty message

Revision ID: 4173e6fe893f
Revises: e9bddc85352d
Create Date: 2019-07-24 17:27:52.787011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4173e6fe893f'
down_revision = 'e9bddc85352d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'data_trust', ['data_trust_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_trust', type_='unique')
    # ### end Alembic commands ###
