"""empty message

Revision ID: 4938ca7b0713
Revises: 5c6f9c67de45
Create Date: 2020-09-28 11:39:45.219605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4938ca7b0713'
down_revision = '5c6f9c67de45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_data_trust_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'data_trust_id')
    op.drop_table('data_trusts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('data_trust_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_data_trust_id_fkey', 'users', 'data_trusts', ['data_trust_id'], ['id'], ondelete='CASCADE')
    op.create_table('data_trusts',
                    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('data_trust_name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('date_last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='data_trusts_pkey'),
                    sa.UniqueConstraint('data_trust_name', name='data_trusts_data_trust_name_key')
                    )
    # ### end Alembic commands ###
