"""empty message

Revision ID: 6d1858d0da0d
Revises: cee6c8486115
Create Date: 2019-07-25 21:07:57.409084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1858d0da0d'
down_revision = 'cee6c8486115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_trusts', sa.Column('date_created', sa.TIMESTAMP(), nullable=True))
    op.add_column('data_trusts', sa.Column('date_last_updated', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_trusts', 'date_last_updated')
    op.drop_column('data_trusts', 'date_created')
    # ### end Alembic commands ###
