"""Associate a user with a role.

Revision ID: 6e27124fd78c
Revises: 4938ca7b0713
Create Date: 2020-09-29 17:41:41.027274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e27124fd78c'
down_revision = '4938ca7b0713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'oauth2_roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
