"""empty message

Revision ID: 7998aa29b531
Revises: 6d1858d0da0d
Create Date: 2019-07-25 23:17:13.097374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7998aa29b531'
down_revision = '6d1858d0da0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_created', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('date_last_updated', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_last_updated')
    op.drop_column('users', 'date_created')
    # ### end Alembic commands ###
