"""empty message

Revision ID: a82b1a6ec9ad
Revises: 00081b33af3b
Create Date: 2019-07-29 19:43:40.524982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82b1a6ec9ad'
down_revision = '00081b33af3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth2_roles', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth2_roles', 'active')
    # ### end Alembic commands ###
