"""empty message

Revision ID: c43ffe7b4001
Revises: ba055915d6e9
Create Date: 2021-04-20 14:54:17.170811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43ffe7b4001'
down_revision = 'ba055915d6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('authorized_clients_user_id_fkey', 'authorized_clients', type_='foreignkey')
    op.create_foreign_key(None, 'authorized_clients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authorized_clients', type_='foreignkey')
    op.create_foreign_key('authorized_clients_user_id_fkey', 'authorized_clients', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
