"""empty message

Revision ID: cee6c8486115
Revises: 91fb9f00304b
Create Date: 2019-07-25 12:44:22.425700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee6c8486115'
down_revision = '91fb9f00304b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('firstname', sa.String(length=40), nullable=False),
    sa.Column('lastname', sa.String(length=40), nullable=False),
    sa.Column('organization', sa.String(length=120), nullable=False),
    sa.Column('email_address', sa.String(length=40), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('data_trust_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['data_trust_id'], ['data_trusts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
