"""Create OAuth2 scope table

Revision ID: d92fa4b2c4f8
Revises: 6e27124fd78c
Create Date: 2020-09-29 19:47:50.314402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92fa4b2c4f8'
down_revision = '6e27124fd78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth2_scopes',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('scope', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('date_created', sa.TIMESTAMP(), nullable=True),
                    sa.Column('date_last_updated', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('scope'),
                    sa.UniqueConstraint('scope')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth2_scopes')
    # ### end Alembic commands ###
