"""Remove Organization from data model.

Revision ID: e0a50f613878
Revises: 3f6cee6eb450
Create Date: 2020-11-04 13:03:05.694147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0a50f613878'
down_revision = '3f6cee6eb450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_organization_id_fkey', 'users', type_='foreignkey')
    op.drop_table('organizations')
    op.add_column('users', sa.Column('person_id', sa.String(), nullable=True))
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'email_address')
    op.drop_column('users', 'telephone')
    op.drop_column('users', 'organization_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('telephone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email_address', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.create_foreign_key('users_organization_id_fkey', 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'person_id')
    op.create_table('organizations',
                    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
                    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('date_last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='organizations_pkey'),
                    sa.UniqueConstraint('name', name='organizations_name_key')
                    )
    # ### end Alembic commands ###
