"""empty message

Revision ID: e9bddc85352d
Revises: 3ec1a5593d88
Create Date: 2019-07-24 17:23:44.563703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9bddc85352d'
down_revision = '3ec1a5593d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('data_trust_data_trust_name_key', 'data_trust', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('data_trust_data_trust_name_key', 'data_trust', ['data_trust_name'])
    # ### end Alembic commands ###
